name: Pagina Test
description: Pagina CMS
dropbox_id: 20301790
dropbox_path: /Pagina/
dropbox_url: https://dl.dropbox.com/u/

# If your Dropbox public link is like this
# http://dl.dropbox.com/u/20301790/Pagina/sitemap.text
# the dropbox_id is the parameter after '/u/'
# and the dropbox_folder is the next parameter

#memcache_ip: 'localhost:11211'
memcache_user: 'pagina'
memcache_pass: '123456'
